version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
<<<<<<< HEAD
=======
    volumes:
      - .:/app
    stdin_open: true
    tty: true

>>>>>>> 2430423db384e53463169ee9bdce68b207bf5042
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
<<<<<<< HEAD
=======
    environment:
      - MONGO_URI=mongodb://mongo:27017/interviewApp
>>>>>>> 2430423db384e53463169ee9bdce68b207bf5042

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
